### ISSUE TITLE
Set env var / option to install binary, even if source is newer?

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/revdepcheck#155] opened 2018-09-25 10:23 UTC
Or make this optional, maybe. Currently it seems the installs fail if a package depends on such a package.

**Comment by hadley** [comment] 2019-04-03 13:37
Is this the cause of this error?

```
Error in if (type == "both") type <- "source" else if (type == "binary") type <- .Platform$pkgType : 
  argument is of length zero
```

**Comment by hadley** [comment] 2019-04-03 13:44
Here's the full traceback:

```
     █
  1. └─revdepcheck::revdep_check(num_workers = 4)
  2.   └─revdepcheck:::revdep_install(pkg, quiet = quiet) /Users/hadley/Documents/r-lib/revdepcheck/R/revdepcheck.R:68:4
  3.     ├─withr::with_envvar(...) /Users/hadley/Documents/r-lib/revdepcheck/R/revdepcheck.R:146:2
  4.     │ └─base::force(code)
  5.     ├─withr::with_libpaths(...) /Users/hadley/Documents/r-lib/revdepcheck/R/revdepcheck.R:146:2
  6.     │ └─base::force(code)
  7.     ├─rlang::with_options(...) /Users/hadley/Documents/r-lib/revdepcheck/R/revdepcheck.R:146:2
  8.     └─remotes::install_local(...) /Users/hadley/Documents/r-lib/revdepcheck/R/revdepcheck.R:146:2
  9.       └─remotes:::install_remotes(...)
 10.         └─base::vapply(remotes, install_remote, ..., FUN.VALUE = character(1))
 11.           └─remotes:::FUN(X[[i]], ...)
 12.             └─remotes:::install(...)
 13.               └─remotes::install_deps(...)
 14.                 ├─stats::update(...)
 15.                 └─remotes:::update.package_deps(...)
 16.                   └─remotes:::install_packages(...)
 17.                     ├─base::do.call(...)
 18.                     └─(function (...) ...
 19.                       ├─remotes:::with_envvar(...)
 20.                       │ └─base::force(code)
 21.                       ├─remotes:::with_options(...)
 22.                       │ └─base::force(code)
 23.                       ├─remotes:::with_rprofile_user("options(warn = 2)", i.p(...))
 24.                       │ ├─remotes:::with_envvar(...)
 25.                       │ │ └─base::force(code)
 26.                       │ └─base::force(code)
 27.                       └─crancache:::i.p(...)
 28.                         ├─crancache:::update_repo_metadata(contriburl)
 29.                         │ └─crancache:::get_packages_urls(contriburl)
 30.                         │   ├─base::structure(...)
 31.                         │   └─base::lapply(contriburl, get_packages_url)
 32.                         └─utils::contrib.url(repos, type)
 33.                           └─utils:::resolvePkgType(type)
```

**Comment by gaborcsardi** [comment] 2019-04-03 13:46
Could very well be. Try setting `R_COMPILE_AND_INSTALL_PACKAGES` to `never`.

**Comment by hadley** [comment] 2019-11-05 13:21
Setting the env var didn't help me, but setting the option did:

```R
options("install.packages.compile.from.source" = "always")
```

**Comment by gaborcsardi** [comment] 2019-11-05 13:33
So there are two issues here
* setting this for the initial installs, which AFAIR happen in the same process.
* setting it for the revdep installs, which happen in subprocesses.

We already set it to never for the redveps (https://github.com/r-lib/revdepcheck/blob/master/R/check.R#L92).

**Comment by hadley** [comment] 2020-05-02 14:04
Duplicate of #243

**Closed by hadley** 2020-05-02 14:04 UTC
