### ISSUE TITLE
set 'options(warn = 1)' explicitly to avoid process termination

### ISSUE THREAD

**Issue by kevinushey** [r-lib/revdepcheck#147] opened 2018-06-04 16:41 UTC
Otherwise things like this can happen:

```
── INIT ─────────────────────────────────────────────────── Computing revdeps ──
── INSTALL ─────────────────────────────────────────────────────── 2 versions ──
Installing CRAN version of RcppRoll
also installing the dependency 'Rcpp'

Installing DEV version of RcppRoll
Installing 1 packages: Rcpp
libc++abi.dylib: terminating with uncaught exception of type Rcpp::eval_error: Evaluation error: (converted from warning) call dbDisconnect() when finished working with a connection.
Abort trap: 6
```

**Comment by kevinushey** [comment] 2018-06-04 16:42
Alternatively, one could clean up the `RSQLite` connections when appropriate, or just establish transient connections to the database as needed (if that's suitable)

**Comment by gaborcsardi** [comment] 2018-06-04 19:51
So, this is because you set  `options(warn =2)`, right? So if you simply don't set that, the problem goes away, no?

**Comment by kevinushey** [comment] 2018-06-04 21:15
I'm setting this in my `.Rprofile`, but for whatever reason it seems to be applied even if I attempt to launch the R process with `--vanilla`. Even with that, I think the onus is on `revdepcheck` to clean up its SQLite connections so this warning is never emitted.

**Comment by gaborcsardi** [comment] 2018-06-04 21:28
> I'm setting this in my .Rprofile

Note that that leads all kinds of failures, because even base R code is not prepared to give up resources when throwing a warning. In general, a lot of R code expects that it can continue running after a warning.

>  I think the onus is on revdepcheck to clean up its SQLite connections

That connection is used until the end of the R session (or until revdepcheck is unloaded), so I am not sure why you see that error at all.

Anyway, let me try to reproduce it.

**Comment by gaborcsardi** [comment] 2018-06-05 10:03
I think the connection warning was coming from the  cranlike package, and should be fixed in the dev version.

**Comment by hadley** [comment] 2020-05-02 14:07
And more db cleanup done in #250

**Closed by hadley** 2020-05-02 14:07 UTC
