### ISSUE TITLE
Package installation fails if dependencies have newer source available

### ISSUE THREAD

**Issue by colearendt** [r-lib/revdepcheck#233] opened 2020-02-09 19:12 UTC
On platforms with binaries (Mac / Windows), it seems that the handling of this condition is done improperly in `revdepcheck`. I have unfortunately not found a way to make this functional (tried both options, tried non-interactive, etc.) since it is in the bootstrapping of the environment 😞 

`rJava` is canonically a weird beast, but this seems to be unrelated so far as I can tell (this worked fine on a brief test on linux).

```
revdepcheck::revdep_check()
── INSTALL ─────────────────────────────────────────────────────── 2 versions ──
Installing CRAN version of xlsx
also installing the dependencies 'rJava', 'xlsxjars'
  There is a binary version available but the source version is later:
      binary source needs_compilation
rJava 0.9-10 0.9-11              TRUE
Do you want to install from sources the package which needs compilation?
y/n: y
Error in download.file(url, destfile, method, mode = "wb", ...) :
  unused argument (upgrade = "always")
Error in download.packages(pkgs, destdir = tmpd, available = available,  :
  (converted from warning) download of package 'xlsxjars' failed
```

Trying with N:
```
revdepcheck::revdep_check()
── INSTALL ─────────────────────────────────────────────────────── 2 versions ──
Installing CRAN version of xlsx
also installing the dependencies 'rJava', 'xlsxjars'
  There is a binary version available but the source version is later:
      binary source needs_compilation
rJava 0.9-10 0.9-11              TRUE
Do you want to install from sources the package which needs compilation?
y/n: n
Error in download.file(url, destfile, method, mode = "wb", ...) :
  unused argument (upgrade = "always")
Error in download.packages(pkgs, destdir = tmpd, available = available,  :
  (converted from warning) download of package 'rJava' failed
```

**Comment by hadley** [comment] 2020-05-02 13:29
Duplicate of #243

**Closed by hadley** 2020-05-02 13:29 UTC
