### ISSUE TITLE
 formal argument "repos" matched by multiple actual arguments

### ISSUE THREAD

**Issue by jeroen** [r-lib/revdepcheck#151] opened 2018-07-09 10:31 UTC
Using current master branch. Only happens in rstudio but not R console.

```
> revdepcheck::revdep_check()
── INIT ──────────────────────────────────────────────────────────────────────────────────────────────── Computing revdeps ──
── INSTALL ──────────────────────────────────────────────────────────────────────────────────────────────────── 2 versions ──
Installing CRAN version of spelling
Installing DEV version of spelling
Error in i.p(...) : 
  formal argument "repos" matched by multiple actual arguments
In addition: Warning message:
call dbDisconnect() when finished working with a connection 
> getOption('repos')
                       CRAN 
"https://cran.rstudio.com/" 
attr(,"RStudio")
[1] TRUE
> 
```

**Comment by bbolker** [comment] 2018-08-13 00:52
I saw this too, but **not** reproducibly:

```
R Under development (unstable) (2018-08-07 r75079)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)
```

after running 

```
source("https://bioconductor.org/biocLite.R")
options(repos=BiocInstaller::biocinstallRepos())
revdep_check("lme4",num_workers=6,timeout=4800)
```

**Comment by hadley** [comment] 2020-05-02 14:06
Seems to be fixed now?

**Closed by hadley** 2020-05-02 14:06 UTC
