### ISSUE TITLE
option to revdep the new package only

### ISSUE THREAD

**Issue by rhijmans** [r-lib/revdepcheck#212] opened 2019-05-12 22:38 UTC
It would help me a lot to have an option to check the new package only. For a package with many dependencies it can take many hours to run revdep_check. The benefit of comparing with the old version may not outweigh the cost of false positives (as most false positives will be known from previous releases). Thanks.

**Comment by hadley** [comment] 2020-05-02 13:45
Now a duplicate of #69

**Closed by hadley** 2020-05-02 13:45 UTC
