### ISSUE TITLE
Suggestion: allow finer control of checking process

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/revdepcheck#232] opened 2020-01-27 05:53 UTC
Eg right now, you need to run `revdep_check` before adding and removing individual packages with `revdep_add` and `revdep_rm`. It would be nice to be able to do the latter independently.

Similarly, `revdep_check` checks all revdeps, with the only control being the `dependencies` argument which is very broad. it would be nice to be able to supply a list of specific packages to check.

**Comment by gaborcsardi** [comment] 2020-01-27 09:22
You can start the check, wait until the actual checks start, press CTRL+C or ESC to stop, then add and remove packages as you like, and then start the check again.

**Comment by Hong-Revo** [comment] 2020-01-27 12:55
That's true, but I was thinking more of a batch/pipeline situation. Would it be difficult to make these changes?

**Comment by gaborcsardi** [comment] 2020-01-27 18:10
It is not very difficult. We don't really run revdepchecks automatically, because they typically require a human eye, so it would be distracting to run them all the time. We only run them before release or after a major change.

You can see the `revdep_check()` function to see how to do the individual steps manually.

**Comment by hadley** [comment] 2020-05-02 13:29
Now duplicate of #69

**Closed by hadley** 2020-05-02 13:29 UTC
